In [26]:
import torch
from transformers import GPT2Tokenizer, GPT2Model, GPT2LMHeadModel
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2Model.from_pretrained('gpt2')
text = "hello"
encoded_input = tokenizer(text, return_tensors='pt')
# output = model(**encoded_input)
gpt2 = GPT2LMHeadModel.from_pretrained('gpt2')

logits = gpt2(**encoded_input).logits
tokenizer.decode(torch.argmax(logits[0,-1,:]))

/home/zkr/miniconda3/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


','

In [27]:
lm_head = gpt2.lm_head

In [30]:
import torch
from transformers import GPT2Tokenizer, GPT2LMHeadModel

# 1. 准备
tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
model = GPT2LMHeadModel.from_pretrained('gpt2') 
text = "The quick brown fox jumps"
encoded_input = tokenizer(text, return_tensors='pt')

# 2. 核心：设置 output_hidden_states=True
output = model(**encoded_input, output_hidden_states=True)

# output 现在包含更多的信息，包括：
# - logits
# - past_key_values (如果有)
# - hidden_states (我们需要的)

/home/zkr/miniconda3/envs/internlm/lib/python3.10/site-packages/huggingface_hub/file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [ ]:
output.hidden_states

(tensor([[[-0.0874, -0.2177,  0.0685,  ...,  0.0208,  0.0183,  0.0576],
          [ 0.0156, -0.0840,  0.1020,  ...,  0.0561, -0.0880, -0.0073],
          [-0.0475,  0.0343,  0.1346,  ...,  0.1119,  0.3051,  0.1437],
          [ 0.1004, -0.0728,  0.2178,  ..., -0.1144,  0.1940, -0.0032],
          [-0.0545, -0.0325,  0.1644,  ...,  0.0436,  0.0666, -0.1314]]],
        grad_fn=<AddBackward0>),
 tensor([[[ 0.1559, -0.7946,  0.3943,  ..., -1.7854, -0.4689,  0.1554],
          [ 0.7071, -0.7694, -1.7236,  ..., -0.8468,  0.6631, -1.2873],
          [ 2.3635,  2.1283, -1.3632,  ..., -0.7981,  0.6089,  0.0814],
          [-1.6026,  1.2453, -0.9453,  ..., -0.8529,  0.0730,  1.0536],
          [-0.7293, -0.5154, -1.5626,  ..., -0.5905,  1.2319,  0.5545]]],
        grad_fn=<AddBackward0>),
 tensor([[[ 0.0386, -1.1676,  1.1246,  ..., -1.4047, -0.5742, -0.0668],
          [ 1.5488, -0.6763, -1.0692,  ..., -1.0627,  0.7097, -2.0730],
          [ 3.1896,  1.6374, -1.2871,  ..., -1.4959,  1.0106, -0.6

# LogitLen

In [33]:
for h_l in output.hidden_states:
    logits = lm_head(h_l)
    res = tokenizer.decode(torch.argmax(logits[0,-1,:]))
    print(res)

 jumps
 jump
 jump
 in
 the
 the
 the
 the
 the
 in
 in
,
 up
